# Face Detection using OpenCV

![face_detection](face_detec.jpg)

In [4]:
# import libraries
import cv2 # OpenCv libarary

In [5]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml") # load harcascade classifier (It contain the face featuers)

# Discription
1. detectMultiScale (Method to search for the face rectangle co-ordinates)
2. scaleFactor (Decrease the shape value by 5%, until the face is found. Smaller the value greater is the accuracy)

In [11]:
img = cv2.imread('zing.jpg')
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # convert color image into gray scale
faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.05, minNeighbors = 5) #search co-ordinates of the image
print(type(faces))
print(faces)

<class 'numpy.ndarray'>
[[3084 1172  267  267]
 [2533 1194  338  338]
 [2162 1360  386  386]
 [1379 1364  707  707]
 [ 406 1564 1089 1089]
 [2515 1846   56   56]
 [ 260 2824  118  118]
 [ 729 2812  168  168]
 [2994 2528  232  232]
 [2806 1285  309  309]
 [3045 1761   91   91]
 [2039 2356   68   68]
 [2988  694  288  288]
 [2909  787  158  158]
 [3317 1571  275  275]]


# Add rectangular FaceBox

# Discription
1. rectangle (method to create the rectangle on face)
2. img (object of the image)
3. x+w, y+h (co-ordinates of the image)
4. 0,255,0 (RGB values of th erectangle)
5. 3 (width of the rectangular box)

In [12]:
for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0), 3)

In [13]:
resize = cv2.resize(img, (int(img.shape[1]/7), int(img.shape[0]/7))) # for resizing the image to see properly

In [16]:
cv2.imshow("Gray", resize)
cv2.waitKey(0)
cv2.destroyAllWindows()